spring:
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Tokyo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
